// Generated by RebrewU -- do not edit
#include <rebrewu_runtime.h>
#include <stdint.h>
#include <math.h>

#include "Gambit.h"

// fn_C0007B30 @ 0xc0007b30
void Gambit_fn_C0007B30(CPUState* cpu) {
  L_C0007B30: ; // 0xc0007b30
        /* C0007B30 */ /* nop */
        /* C0007B34 */ /* nop */
        /* C0007B38 */ /* nop */
        /* C0007B3C */ /* nop */
        /* C0007B40 */ /* nop */
        /* C0007B44 */ /* nop */
        /* C0007B48 */ /* nop */
        /* C0007B4C */ /* nop */
        /* C0007B50 */ /* nop */
        /* C0007B54 */ /* nop */
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B38 @ 0xc0007b38
void Gambit_fn_C0007B38(CPUState* cpu) {
  L_C0007B38: ; // 0xc0007b38
        /* C0007B38 */ /* nop */
        /* C0007B3C */ /* nop */
        /* C0007B40 */ /* nop */
        /* C0007B44 */ /* nop */
        /* C0007B48 */ /* nop */
        /* C0007B4C */ /* nop */
        /* C0007B50 */ /* nop */
        /* C0007B54 */ /* nop */
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B40 @ 0xc0007b40
void Gambit_fn_C0007B40(CPUState* cpu) {
  L_C0007B40: ; // 0xc0007b40
        /* C0007B40 */ /* nop */
        /* C0007B44 */ /* nop */
        /* C0007B48 */ /* nop */
        /* C0007B4C */ /* nop */
        /* C0007B50 */ /* nop */
        /* C0007B54 */ /* nop */
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B48 @ 0xc0007b48
void Gambit_fn_C0007B48(CPUState* cpu) {
  L_C0007B48: ; // 0xc0007b48
        /* C0007B48 */ /* nop */
        /* C0007B4C */ /* nop */
        /* C0007B50 */ /* nop */
        /* C0007B54 */ /* nop */
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B50 @ 0xc0007b50
void Gambit_fn_C0007B50(CPUState* cpu) {
  L_C0007B50: ; // 0xc0007b50
        /* C0007B50 */ /* nop */
        /* C0007B54 */ /* nop */
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B58 @ 0xc0007b58
void Gambit_fn_C0007B58(CPUState* cpu) {
  L_C0007B58: ; // 0xc0007b58
        /* C0007B58 */ /* nop */
        /* C0007B5C */ /* nop */
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B60 @ 0xc0007b60
void Gambit_fn_C0007B60(CPUState* cpu) {
  L_C0007B60: ; // 0xc0007b60
        /* C0007B60 */ /* nop */
        /* C0007B64 */ /* nop */
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B68 @ 0xc0007b68
void Gambit_fn_C0007B68(CPUState* cpu) {
  L_C0007B68: ; // 0xc0007b68
        /* C0007B68 */ /* nop */
        /* C0007B6C */ /* nop */
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B70 @ 0xc0007b70
void Gambit_fn_C0007B70(CPUState* cpu) {
  L_C0007B70: ; // 0xc0007b70
        /* C0007B70 */ /* nop */
        /* C0007B74 */ /* nop */
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B78 @ 0xc0007b78
void Gambit_fn_C0007B78(CPUState* cpu) {
  L_C0007B78: ; // 0xc0007b78
        /* C0007B78 */ /* nop */
        /* C0007B7C */ /* nop */
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B80 @ 0xc0007b80
void Gambit_fn_C0007B80(CPUState* cpu) {
  L_C0007B80: ; // 0xc0007b80
        /* C0007B80 */ /* nop */
        /* C0007B84 */ /* nop */
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B88 @ 0xc0007b88
void Gambit_fn_C0007B88(CPUState* cpu) {
  L_C0007B88: ; // 0xc0007b88
        /* C0007B88 */ /* nop */
        /* C0007B8C */ /* nop */
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B90 @ 0xc0007b90
void Gambit_fn_C0007B90(CPUState* cpu) {
  L_C0007B90: ; // 0xc0007b90
        /* C0007B90 */ /* nop */
        /* C0007B94 */ /* nop */
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007B98 @ 0xc0007b98
void Gambit_fn_C0007B98(CPUState* cpu) {
  L_C0007B98: ; // 0xc0007b98
        /* C0007B98 */ /* nop */
        /* C0007B9C */ /* nop */
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BA0 @ 0xc0007ba0
void Gambit_fn_C0007BA0(CPUState* cpu) {
  L_C0007BA0: ; // 0xc0007ba0
        /* C0007BA0 */ /* nop */
        /* C0007BA4 */ /* nop */
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BA8 @ 0xc0007ba8
void Gambit_fn_C0007BA8(CPUState* cpu) {
  L_C0007BA8: ; // 0xc0007ba8
        /* C0007BA8 */ /* nop */
        /* C0007BAC */ /* nop */
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BB0 @ 0xc0007bb0
void Gambit_fn_C0007BB0(CPUState* cpu) {
  L_C0007BB0: ; // 0xc0007bb0
        /* C0007BB0 */ /* nop */
        /* C0007BB4 */ /* nop */
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BB8 @ 0xc0007bb8
void Gambit_fn_C0007BB8(CPUState* cpu) {
  L_C0007BB8: ; // 0xc0007bb8
        /* C0007BB8 */ /* nop */
        /* C0007BBC */ /* nop */
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BC0 @ 0xc0007bc0
void Gambit_fn_C0007BC0(CPUState* cpu) {
  L_C0007BC0: ; // 0xc0007bc0
        /* C0007BC0 */ /* nop */
        /* C0007BC4 */ /* nop */
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BC8 @ 0xc0007bc8
void Gambit_fn_C0007BC8(CPUState* cpu) {
  L_C0007BC8: ; // 0xc0007bc8
        /* C0007BC8 */ /* nop */
        /* C0007BCC */ /* nop */
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BD0 @ 0xc0007bd0
void Gambit_fn_C0007BD0(CPUState* cpu) {
  L_C0007BD0: ; // 0xc0007bd0
        /* C0007BD0 */ /* nop */
        /* C0007BD4 */ /* nop */
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BD8 @ 0xc0007bd8
void Gambit_fn_C0007BD8(CPUState* cpu) {
  L_C0007BD8: ; // 0xc0007bd8
        /* C0007BD8 */ /* nop */
        /* C0007BDC */ /* nop */
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BE0 @ 0xc0007be0
void Gambit_fn_C0007BE0(CPUState* cpu) {
  L_C0007BE0: ; // 0xc0007be0
        /* C0007BE0 */ /* nop */
        /* C0007BE4 */ /* nop */
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BE8 @ 0xc0007be8
void Gambit_fn_C0007BE8(CPUState* cpu) {
  L_C0007BE8: ; // 0xc0007be8
        /* C0007BE8 */ /* nop */
        /* C0007BEC */ /* nop */
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BF0 @ 0xc0007bf0
void Gambit_fn_C0007BF0(CPUState* cpu) {
  L_C0007BF0: ; // 0xc0007bf0
        /* C0007BF0 */ /* nop */
        /* C0007BF4 */ /* nop */
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007BF8 @ 0xc0007bf8
void Gambit_fn_C0007BF8(CPUState* cpu) {
  L_C0007BF8: ; // 0xc0007bf8
        /* C0007BF8 */ /* nop */
        /* C0007BFC */ /* nop */
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C00 @ 0xc0007c00
void Gambit_fn_C0007C00(CPUState* cpu) {
  L_C0007C00: ; // 0xc0007c00
        /* C0007C00 */ /* nop */
        /* C0007C04 */ /* nop */
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C08 @ 0xc0007c08
void Gambit_fn_C0007C08(CPUState* cpu) {
  L_C0007C08: ; // 0xc0007c08
        /* C0007C08 */ /* nop */
        /* C0007C0C */ /* nop */
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C10 @ 0xc0007c10
void Gambit_fn_C0007C10(CPUState* cpu) {
  L_C0007C10: ; // 0xc0007c10
        /* C0007C10 */ /* nop */
        /* C0007C14 */ /* nop */
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C18 @ 0xc0007c18
void Gambit_fn_C0007C18(CPUState* cpu) {
  L_C0007C18: ; // 0xc0007c18
        /* C0007C18 */ /* nop */
        /* C0007C1C */ /* nop */
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C20 @ 0xc0007c20
void Gambit_fn_C0007C20(CPUState* cpu) {
  L_C0007C20: ; // 0xc0007c20
        /* C0007C20 */ /* nop */
        /* C0007C24 */ /* nop */
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C28 @ 0xc0007c28
void Gambit_fn_C0007C28(CPUState* cpu) {
  L_C0007C28: ; // 0xc0007c28
        /* C0007C28 */ /* nop */
        /* C0007C2C */ /* nop */
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C30 @ 0xc0007c30
void Gambit_fn_C0007C30(CPUState* cpu) {
  L_C0007C30: ; // 0xc0007c30
        /* C0007C30 */ /* nop */
        /* C0007C34 */ /* nop */
}

// fn_C0007C80 @ 0xc0007c80
void Gambit_fn_C0007C80(CPUState* cpu) {
  L_C0007C80: ; // 0xc0007c80
        /* C0007C80 */ /* nop */
        /* C0007C84 */ cpu->r[11] = cpu->r[18] + 0x0000530Bu;
        /* C0007C88 */ cpu->r[14] = cpu->r[19] ^ 0x5F660000u;
        /* C0007C8C */ cpu->r[0] = cpu->r[0] & 0x00000000u;
        /* C0007C8C */ cpu->cr[0] = rbrew_cmp_s32(cpu->r[0], 0x00000000u);
        /* C0007C90 */ /* nop */
        /* C0007C94 */ /* nop */
        /* C0007C98 */ /* nop */
        /* C0007C9C */ /* nop */
        /* C0007CA0 */ /* nop */
        /* C0007CA4 */ /* nop */
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007C88 @ 0xc0007c88
void Gambit_fn_C0007C88(CPUState* cpu) {
  L_C0007C88: ; // 0xc0007c88
        /* C0007C88 */ cpu->r[14] = cpu->r[19] ^ 0x5F660000u;
        /* C0007C8C */ cpu->r[0] = cpu->r[0] & 0x00000000u;
        /* C0007C8C */ cpu->cr[0] = rbrew_cmp_s32(cpu->r[0], 0x00000000u);
        /* C0007C90 */ /* nop */
        /* C0007C94 */ /* nop */
        /* C0007C98 */ /* nop */
        /* C0007C9C */ /* nop */
        /* C0007CA0 */ /* nop */
        /* C0007CA4 */ /* nop */
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007C90 @ 0xc0007c90
void Gambit_fn_C0007C90(CPUState* cpu) {
  L_C0007C90: ; // 0xc0007c90
        /* C0007C90 */ /* nop */
        /* C0007C94 */ /* nop */
        /* C0007C98 */ /* nop */
        /* C0007C9C */ /* nop */
        /* C0007CA0 */ /* nop */
        /* C0007CA4 */ /* nop */
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007C98 @ 0xc0007c98
void Gambit_fn_C0007C98(CPUState* cpu) {
  L_C0007C98: ; // 0xc0007c98
        /* C0007C98 */ /* nop */
        /* C0007C9C */ /* nop */
        /* C0007CA0 */ /* nop */
        /* C0007CA4 */ /* nop */
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CA0 @ 0xc0007ca0
void Gambit_fn_C0007CA0(CPUState* cpu) {
  L_C0007CA0: ; // 0xc0007ca0
        /* C0007CA0 */ /* nop */
        /* C0007CA4 */ /* nop */
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CA8 @ 0xc0007ca8
void Gambit_fn_C0007CA8(CPUState* cpu) {
  L_C0007CA8: ; // 0xc0007ca8
        /* C0007CA8 */ /* nop */
        /* C0007CAC */ /* nop */
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CB0 @ 0xc0007cb0
void Gambit_fn_C0007CB0(CPUState* cpu) {
  L_C0007CB0: ; // 0xc0007cb0
        /* C0007CB0 */ /* nop */
        /* C0007CB4 */ /* nop */
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CB8 @ 0xc0007cb8
void Gambit_fn_C0007CB8(CPUState* cpu) {
  L_C0007CB8: ; // 0xc0007cb8
        /* C0007CB8 */ /* nop */
        /* C0007CBC */ /* nop */
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CC0 @ 0xc0007cc0
void Gambit_fn_C0007CC0(CPUState* cpu) {
  L_C0007CC0: ; // 0xc0007cc0
        /* C0007CC0 */ /* nop */
        /* C0007CC4 */ /* nop */
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CC8 @ 0xc0007cc8
void Gambit_fn_C0007CC8(CPUState* cpu) {
  L_C0007CC8: ; // 0xc0007cc8
        /* C0007CC8 */ /* nop */
        /* C0007CCC */ /* nop */
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CD0 @ 0xc0007cd0
void Gambit_fn_C0007CD0(CPUState* cpu) {
  L_C0007CD0: ; // 0xc0007cd0
        /* C0007CD0 */ /* nop */
        /* C0007CD4 */ /* nop */
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CD8 @ 0xc0007cd8
void Gambit_fn_C0007CD8(CPUState* cpu) {
  L_C0007CD8: ; // 0xc0007cd8
        /* C0007CD8 */ /* nop */
        /* C0007CDC */ /* nop */
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CE0 @ 0xc0007ce0
void Gambit_fn_C0007CE0(CPUState* cpu) {
  L_C0007CE0: ; // 0xc0007ce0
        /* C0007CE0 */ /* nop */
        /* C0007CE4 */ /* nop */
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CE8 @ 0xc0007ce8
void Gambit_fn_C0007CE8(CPUState* cpu) {
  L_C0007CE8: ; // 0xc0007ce8
        /* C0007CE8 */ /* nop */
        /* C0007CEC */ /* nop */
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CF0 @ 0xc0007cf0
void Gambit_fn_C0007CF0(CPUState* cpu) {
  L_C0007CF0: ; // 0xc0007cf0
        /* C0007CF0 */ /* nop */
        /* C0007CF4 */ /* nop */
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007CF8 @ 0xc0007cf8
void Gambit_fn_C0007CF8(CPUState* cpu) {
  L_C0007CF8: ; // 0xc0007cf8
        /* C0007CF8 */ /* nop */
        /* C0007CFC */ /* nop */
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007D00 @ 0xc0007d00
void Gambit_fn_C0007D00(CPUState* cpu) {
  L_C0007D00: ; // 0xc0007d00
        /* C0007D00 */ /* nop */
        /* C0007D04 */ /* nop */
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007D08 @ 0xc0007d08
void Gambit_fn_C0007D08(CPUState* cpu) {
  L_C0007D08: ; // 0xc0007d08
        /* C0007D08 */ /* nop */
        /* C0007D0C */ /* nop */
}

// fn_C0007D40 @ 0xc0007d40
void Gambit_fn_C0007D40(CPUState* cpu) {
    uint32_t _t0;

  L_C0007D40: ; // 0xc0007d40
        /* C0007D40 */ /* nop */
        /* C0007D44 */ _t0 = cpu->r[9] + 0x00006CF5u;
        /* C0007D44 */ cpu->f[13] = rbrew_read_f32(cpu->mem, _t0);
        /* C0007D48 */ cpu->r[14] = cpu->r[19] ^ 0x5F6E0000u;
        /* C0007D4C */ cpu->r[13] = cpu->r[3] | 0x00000000u;
        /* C0007D50 */ /* nop */
        /* C0007D54 */ /* nop */
        /* C0007D58 */ /* nop */
        /* C0007D5C */ /* nop */
        /* C0007D60 */ /* nop */
        /* C0007D64 */ /* nop */
}

// fn_C0007D48 @ 0xc0007d48
void Gambit_fn_C0007D48(CPUState* cpu) {
  L_C0007D48: ; // 0xc0007d48
        /* C0007D48 */ cpu->r[14] = cpu->r[19] ^ 0x5F6E0000u;
        /* C0007D4C */ cpu->r[13] = cpu->r[3] | 0x00000000u;
        /* C0007D50 */ /* nop */
        /* C0007D54 */ /* nop */
        /* C0007D58 */ /* nop */
        /* C0007D5C */ /* nop */
        /* C0007D60 */ /* nop */
        /* C0007D64 */ /* nop */
}

// fn_C0007D50 @ 0xc0007d50
void Gambit_fn_C0007D50(CPUState* cpu) {
  L_C0007D50: ; // 0xc0007d50
        /* C0007D50 */ /* nop */
        /* C0007D54 */ /* nop */
        /* C0007D58 */ /* nop */
        /* C0007D5C */ /* nop */
        /* C0007D60 */ /* nop */
        /* C0007D64 */ /* nop */
}

// fn_C0007D58 @ 0xc0007d58
void Gambit_fn_C0007D58(CPUState* cpu) {
  L_C0007D58: ; // 0xc0007d58
        /* C0007D58 */ /* nop */
        /* C0007D5C */ /* nop */
        /* C0007D60 */ /* nop */
        /* C0007D64 */ /* nop */
}

// fn_C0007D60 @ 0xc0007d60
void Gambit_fn_C0007D60(CPUState* cpu) {
  L_C0007D60: ; // 0xc0007d60
        /* C0007D60 */ /* nop */
        /* C0007D64 */ /* nop */
}

// fn_C0007D80 @ 0xc0007d80
void Gambit_fn_C0007D80(CPUState* cpu) {
  L_C0007D80: ; // 0xc0007d80
        /* C0007D80 */ /* nop */
        /* C0007D84 */ rbrew_dispatch(cpu, 0xff136facu);
        /* C0007D88 */ cpu->r[14] = cpu->r[19] ^ 0x5F6E0000u;
        /* C0007D8C */ cpu->r[16] = cpu->r[19] | 0x00000000u;
        /* C0007D90 */ /* nop */
        /* C0007D94 */ /* nop */
        /* C0007D98 */ /* nop */
        /* C0007D9C */ /* nop */
        /* C0007DA0 */ /* nop */
        /* C0007DA4 */ /* nop */
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007D88 @ 0xc0007d88
void Gambit_fn_C0007D88(CPUState* cpu) {
  L_C0007D88: ; // 0xc0007d88
        /* C0007D88 */ cpu->r[14] = cpu->r[19] ^ 0x5F6E0000u;
        /* C0007D8C */ cpu->r[16] = cpu->r[19] | 0x00000000u;
        /* C0007D90 */ /* nop */
        /* C0007D94 */ /* nop */
        /* C0007D98 */ /* nop */
        /* C0007D9C */ /* nop */
        /* C0007DA0 */ /* nop */
        /* C0007DA4 */ /* nop */
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007D90 @ 0xc0007d90
void Gambit_fn_C0007D90(CPUState* cpu) {
  L_C0007D90: ; // 0xc0007d90
        /* C0007D90 */ /* nop */
        /* C0007D94 */ /* nop */
        /* C0007D98 */ /* nop */
        /* C0007D9C */ /* nop */
        /* C0007DA0 */ /* nop */
        /* C0007DA4 */ /* nop */
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007D98 @ 0xc0007d98
void Gambit_fn_C0007D98(CPUState* cpu) {
  L_C0007D98: ; // 0xc0007d98
        /* C0007D98 */ /* nop */
        /* C0007D9C */ /* nop */
        /* C0007DA0 */ /* nop */
        /* C0007DA4 */ /* nop */
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DA0 @ 0xc0007da0
void Gambit_fn_C0007DA0(CPUState* cpu) {
  L_C0007DA0: ; // 0xc0007da0
        /* C0007DA0 */ /* nop */
        /* C0007DA4 */ /* nop */
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DA8 @ 0xc0007da8
void Gambit_fn_C0007DA8(CPUState* cpu) {
  L_C0007DA8: ; // 0xc0007da8
        /* C0007DA8 */ /* nop */
        /* C0007DAC */ /* nop */
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DB0 @ 0xc0007db0
void Gambit_fn_C0007DB0(CPUState* cpu) {
  L_C0007DB0: ; // 0xc0007db0
        /* C0007DB0 */ /* nop */
        /* C0007DB4 */ /* nop */
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DB8 @ 0xc0007db8
void Gambit_fn_C0007DB8(CPUState* cpu) {
  L_C0007DB8: ; // 0xc0007db8
        /* C0007DB8 */ /* nop */
        /* C0007DBC */ /* nop */
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DC0 @ 0xc0007dc0
void Gambit_fn_C0007DC0(CPUState* cpu) {
  L_C0007DC0: ; // 0xc0007dc0
        /* C0007DC0 */ /* nop */
        /* C0007DC4 */ /* nop */
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DC8 @ 0xc0007dc8
void Gambit_fn_C0007DC8(CPUState* cpu) {
  L_C0007DC8: ; // 0xc0007dc8
        /* C0007DC8 */ /* nop */
        /* C0007DCC */ /* nop */
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DD0 @ 0xc0007dd0
void Gambit_fn_C0007DD0(CPUState* cpu) {
  L_C0007DD0: ; // 0xc0007dd0
        /* C0007DD0 */ /* nop */
        /* C0007DD4 */ /* nop */
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

// fn_C0007DD8 @ 0xc0007dd8
void Gambit_fn_C0007DD8(CPUState* cpu) {
  L_C0007DD8: ; // 0xc0007dd8
        /* C0007DD8 */ /* nop */
        /* C0007DDC */ /* nop */
}

